### ISSUE TITLE
Breezy / patiencediff dependency

### ISSUE THREAD

**Issue by Treora** [pierstitus/klondiff#2]
From the readme:

> Requires python3 and python3-breezy to be installed.

I guess you refer to the python3-breezy ubuntu/debian package? In any case, I tried to just install with pip: `pip3 install breezy`. However, it appears not to contain the patiencediff implementation that klondiff attempts to import from it.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/clones/klondiff/patiencediff.py", line 225, in <module>
    from breezy._patiencediff_py import (
ModuleNotFoundError: No module named 'breezy._patiencediff_py'
```

Might it have disappeared from some version? The underscore before the name suggests that it is not supposed to be relied upon. However it looks like the patiencediff is also published as a package itself: <https://pypi.org/project/patiencediff/>. Might you not rather depend on that instead?

I got it to work by installing it (`pip3 install patiencediff`), then changing lines [218–229](https://github.com/pierstitus/klondiff/blob/647ddf16dae4ba017cbc2f9f6c1f55736a4d6ad3/patiencediff.py#L218-L229) in klondiff’s `patiencediff.py` to simply be:

```
from patiencediff import (
    unique_lcs,
    recurse_matches,
    PatienceSequenceMatcher
    )
```

It looks like the patiencediff package exports either the C or Python implementation.

Note I had to change the filename (and the symlink pointing to it) so it would not attempt to import itself.

**Comment by pierstitus** [comment]
Thanks for the suggestion, good to hear that patiencediff is also packaged separately now, that makes the dependency a lot cleaner.
